# Generated by Django 5.2.11 on 2026-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_learningsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='duration_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
